settings.gradle.kts

K/N adds an Ivy repository dynamically to download the K/N compiler, so we cannot enforce repositories to be declared in `settings.gradle.kts`.

Removes the repositoriesMode setting. 

---

core/api/core.api
core/src/androidMain/kotlin/io/shortway/kobankat/Package.android.kt
core/src/commonMain/kotlin/io/shortway/kobankat/Package.kt
core/src/iosMain/kotlin/io/shortway/kobankat/Package.ios.kt

Avoid type error by renaming Package.product to Package.storeProduct

---

.circleci/config.yml
.sdkmanrc
build-logic/convention/src/main/kotlin/com/revenuecat/purchases/kmp/buildlogic/plugin/LibraryConventionPlugin.kt
build.gradle.kts
core/api/core.klib.api
datetime/api/datetime.klib.api
either/api/either.klib.api
gradle/libs.versions.toml
paywalls/api/paywalls.klib.api
result/api/result.klib.api

- Adds a CircleCI config with a `deploy-snapshot` job that runs for all pushes to `main`. 
- Removes the NmcpPlugin, which I had to use in KobanKat. I had created my Maven Central account after a certain date which meant I could only publish via the [Central Portal](https://central.sonatype.org/register/central-portal/), and `com.vanniktech.maven.publish` did not have support for that at that time. (See https://github.com/vanniktech/gradle-maven-publish-plugin/issues/722.)
- Adjusts the coordinates and POM file to contain RevenueCat info instead of my personal info.
- Updates the klib abi dump, because the group changed (to `com.revenuecat.purchases`).

Adds snapshot publishing

---

core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreMessageType.kt
core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt

- Fixes conversion of `StoreMessageType` to integer in `showInAppMessagesIfNeeded()` by making it more explicit.
- Aligns `StoreMessageType`'s order with [`StoreMessageType.swift`](https://github.com/RevenueCat/purchases-ios/blob/main/Sources/Support/StoreMessageType.swift) in purchases-ios. 
**Note:** it appears `RCStoreMessageType` is not exposed by PHC which is why the integers are magic numbers now. Something we should look into.

Fixes showInAppMessagesIfNeeded() on iOS

---

.circleci/config.yml
fastlane/Fastfile

As the title says. CircleCI is weird. This bug seems to have existed for a long time where workflows with a tag filter need to have the same filter on jobs as well. 
One of many: https://discuss.circleci.com/t/running-a-workflow-after-tagging-commit/49581. 
Without this change, we get a "[No workflow](https://app.circleci.com/pipelines/github/RevenueCat/purchases-kmp/171)" state from CircleCI.  
After this change, [the workflow runs](https://app.circleci.com/pipelines/github/RevenueCat/purchases-kmp/177). 
This is [not supported](https://app.circleci.com/pipelines/github/RevenueCat/purchases-kmp/175/workflows/2c1d41a1-16ad-4b98-af02-6047f9f36763/jobs/251/parallel-runs/0/steps/0-113).

Fixes the release pipeline

---

apiTester/build.gradle.kts

As the title says. This plugin was removed in a previous PR, but was still referenced here. This _should_ make CI go green again.

Removes the Compose Compiler Gradle Plugin from :apiTester.

---

iosApp/iosApp.xcworkspace/contents.xcworkspacedata

This `contents.xcworkspacedata` file allows us to see Kotlin code in the Xcode file browser, however it was broken for paywalls code when we renamed the `paywalls` module to `revenuecatui`. This fixes that. 
Visual reference:

Fixes viewing revenuecatui Kotlin code in Xcode

---

core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/di/AndroidProvider.kt

As the title says. While this should not happen, the previous error message was a bit unhelpful.

Improves the error message when the PurchasesInitializer is missing from the merged AndroidManifest.xml.

---

composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/App.kt
composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/MainScreen.kt
composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/Screen.kt
fastlane/Fastfile
iosApp/Podfile
iosApp/Podfile.lock
revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitPaywall.kt

As the title says. The commit messages are pretty descriptive. The actual fix is tiny and in the last commit.
Closes #128

Fix iOS crash showing paywall for current offering

---

.git-branches.toml

As the title says. Since @vegaro is now also trying out `git-town`, it's beneficial that everyone has the same config, hence this PR.

Adds the git-town config to source control.

---

core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt

As the title says.
1. Pulled `onSuccess` on the same line as `else` in a few places: 
```diff
- else 
-     onSuccess(
+ else onSuccess(
```
2. Then reformatted using CMD+OPTION+L.
3. Lastly, imports were optimized because I have that enabled as a precommit setting in Android Studio. Can be done manually using CTRL+OPTION+O.

Auto-formats Purchases.ios.kt.

---

core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/LogHandler.android.kt
mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/LogHandler.ios.kt

Removes the need for `DefaultLogHandler` by wrapping the native `AndroidLogHandler` if no `LogHandler` has been set yet.

Wraps the native Android LogHandler if necessary

---

core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ktx/Coroutines.kt
either/src/commonMain/kotlin/com/revenuecat/purchases/kmp/either/Either.kt
models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.kt

As the title says. Unfortunately `SuccessfulPurchase` and `SuccessfulLogin` needed to keep their public constructors, because they are constructed in `:result` and `:either`. It's not ideal, but not terrible either imo.

Converts the last few data classes to regular classes.

---

migrations/KobanKat-MIGRATION.md

- Adds a note about not forgetting `pod install`.
- Links to the `1.0.0-beta.3` guide as the one to follow next.

Updates the KobanKat migration guide

---

composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/App.kt
composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/rememberLoggingPaywallListener.kt
revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallOptionsKtx.kt

As the title says. Also added a listener to the tester app, and was able to reproduce it with that. Verified no more crashes on both Android and iOS.
We were unsafely casting, which worked fine before when everything was a type alias. That's no longer the case. `StoreTransaction` was already converted away from a type alias in `1.0.0-beta.3`, and we made it "worse" on `main` by converting the rest. 
For some weird reason we have double Kotlin mappings for the same underlying ObjC class. For now, I'm casting one to the other (which works because it's the same thing), and then calling our mapper function. 
I also checked some other casts we do, and they _seem_ okay so far. 
Closes #168

Fixes a PaywallListener crash

---

migrations/1.0.0-MIGRATION.md
migrations/1.0.0-beta.3-MIGRATION.md

As the title says. Also did some minor updates to the `1.0.0-beta.3` migration guide. Please let me know if you think of something else that should be added!

Adds v1 migration guide

---

core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
iosApp/Podfile.lock
mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Price.ios.kt
mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/PromotionalOffer.ios.kt
mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/StoreProduct.ios.kt
mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/StoreProductDiscount.ios.kt

Since PHC did not expose the actual price amount on iOS, we were reconstructing it by parsing the formatted price string. Besides being very brittle, this might also be the cause of https://github.com/RevenueCat/purchases-kmp/issues/161, as we return `0` if the price formatter is null. The meat of this PR is in `Price.ios.kt`. 
**Note**: this is ready for review. It's just dependent on a few external factors:

Greatly simplifies how Price.amountMicros is determined on iOS.

---

.circleci/config.yml

As the title says. This should fix the release train. ([recent failure](https://app.circleci.com/pipelines/github/RevenueCat/purchases-kmp/512/workflows/4b283678-ceca-473f-8ac0-f8d7b7894ee5/jobs/761))

Passes the right contexts to the automatic-bump job.

---

.gitignore
.idea/vcs.xml

Adds Issue Navigation settings, which makes comments mentioning an issue / PR have a clickable link straight to it:

Makes issue identifiers clickable in Android Studio

---

.circleci/config.yml

We have the Podfile.lock file version controlled. We made sure it gets updated automatically in https://github.com/RevenueCat/purchases-kmp/pull/175, but that requires running a CocoaPods command which [fails on CI](https://app.circleci.com/pipelines/github/RevenueCat/purchases-kmp/579/workflows/2c17864f-f52a-4e67-aac5-fa56244d2e78/jobs/851).
That, in combination with the fact that running the `update_hybrid_common` lane locally in a clean checkout works fine, leads me to believe that the CI job needs to run on macOS. That's what this PR does.

Runs the update-purchases-hybrid-common-version job on macOS.

---

core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.ios.kt

The `PurchasesDelegate` sometimes doesn't get called on iOS.
On the iOS platform side, the backing field of `Purchases.delegate`, `Purchases.privateDelegate`, is a [`weak var`](https://github.com/RevenueCat/purchases-ios/blob/b695ac1866f2fd56c7484b53b003cdc70adcd1ca/Sources/Purchasing/Purchases/Purchases.swift#L105). On the multiplatform side, we wrap the actual delegate in `PurchasesDelegateWrapper` to conform to `RCPurchasesDelegateProtocol`. Since that is a private implementation detail, the only reference held to our wrapper is the `weak var`. This means that it gets deallocated the first chance it gets. 
We keep a strong reference to our `PurchasesDelegateWrapper`. This matches the Android behavior, which keeps a strong reference on the platform side already.
Fixes #203

Fixes the PurchasesDelegate being deallocated on iOS

---

Gemfile.lock

As the title says. Dependabot didn't pick this up for some reason.

Updates Fastlane plugin to 5b2e35c6985e02b5911c53ebe4d071e742e03ccc

---

fastlane/Fastfile

As the title says. This used to error out, but that meant CI would always fail right after a release, before the version is updated to `-SNAPSHOT`. Example [here](https://app.circleci.com/pipelines/github/RevenueCat/purchases-kmp/686/workflows/8c04110b-b29c-4522-8ec9-9587a15c1340/jobs/1613).

Skips publishing SNAPSHOT if the current version is not a SNAPSHOT.

---

Gemfile
Gemfile.lock

We've been getting [this error on CircleC](https://app.circleci.com/pipelines/github/RevenueCat/purchases-kmp/729/workflows/cb0011c8-96a8-4bff-b975-22d611beb331/jobs/2015)I:
> Your bundle is locked to ffi (1.17.0-arm64-darwin) from rubygems repository
https://rubygems.org/ or installed locally, but that version can no longer be
found in that source. That means the author of ffi (1.17.0-arm64-darwin) has
removed it. You'll need to update your bundle to a version other than ffi
(1.17.0-arm64-darwin) that hasn't been removed in order to install. 
However, 1.17.0 is the latest version at the time of writing. Others have similar issues, e.g. see: https://github.com/ffi/ffi/issues/1105. It is mentioned in that thread that the platform specification in `Gemfile.lock` causes the issue. In our …

Attempts to fix ffi by removing the platform specification.

---

fastlane/Fastfile

As the title says. Removes a `!`.

Fixes a typo in the Fastfile

---

apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/OfferingsAPI.kt
mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offerings.android.kt
mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offerings.ios.kt
models/api/models.api
models/api/models.klib.api
models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Offerings.kt

This adds the `Offerings.getCurrentOfferingForPlacement()` functionality back, which was removed in https://github.com/RevenueCat/purchases-kmp/pull/121. 
In order to make this non-breaking, I added a lambda constructor parameter to `Offerings`. I don't entirely love it, but all the alternatives I could think of are breaking in one way or another (e.g. making `Offerings` an interface). Please do let me know all your ideas! I'm also happy to discuss this more. 
- Dependency: https://github.com/RevenueCat/purchases-hybrid-common/pull/938
- Addresses: https://github.com/RevenueCat/purchases-kmp/issues/242

Adds `Offerings.getCurrentOfferingForPlacement()`

---

gradle/libs.versions.toml
iosApp/Podfile.lock

As discussed in a weekly a few _weeks_ ago, [1.7.0 is finally stable](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.7.0). 
- Closes https://github.com/RevenueCat/purchases-kmp/issues/199
- Closes https://github.com/RevenueCat/purchases-kmp/issues/201
Also updates the `Podfile.lock`, because [that pipeline](https://app.circleci.com/pipelines/github/RevenueCat/purchases-kmp/770/workflows/ff5b9f7d-c644-4e03-b663-c259865e20bb/jobs/2386) seems to run too soon, before the new pod is actually published.

Updates Compose Multiplatform to 1.7.0.

---

revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallFooter.kt
revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallOptionsKtx.kt
revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitPaywall.kt

This is a regression introduced by Compose Multiplatform 1.7.0. 
The `PaywallFooter` is not laid out correctly. Its height is correct, but it is placed too low in its container. This only happens on iOS. Android is fine. 
After some experimentation with safe area insets, I found that it is actually caused by `animateContentSize()`. We are using this, because we don't immediately know the height of the footer. So we set it at 0 at first, and then animate it up once we know it. 
Removing the `animateContentSize()` modifier completely fixes the layout. 
I dug a bit deeper, and was actually able to avoid the need for the animation by figuring out the footer height before the first frame is drawn, using `intrinsincContentSize`. This means the footer is immediately of the right height, no …

Fixes iOS PaywallFooter height

---

apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreMessageTypeAPI.kt
core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
models/api/models.api
models/api/models.klib.api
models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreMessageType.kt

This PR introduces the ability for a developer to display deferred StoreKit win-back offer messages to the user. The functionality was originally introduced in https://github.com/RevenueCat/purchases-ios/pull/4343.
Other than the enum addition, no other changes are necessary.

Support displaying deferred win-back StoreKit messages

---

mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfo.ios.kt

While testing web redemptions, I noticed we could crash in iOS if the user had an RCBiling/Web purchase.

Fix crash when mapping store type RCBilling to KMP

---

.circleci/config.yml

I noticed a while back that 2 workflows kick off on release branches (`on-any-branch` and `on-release-branch`), both running the full test suite. This PR fixes that.

Only runs tests once on release branches, instead of twice.

---

apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreAPI.kt
mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/Store.android.kt
mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfo.ios.kt
models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/EntitlementInfo.kt

Depends on https://github.com/RevenueCat/purchases-hybrid-common/pull/1150. Adds the `Paddle` store to KMP.

Add `Paddle` Store

---

core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/di/AndroidProvider.kt

The app would sometimes crash when calling `purchase()`, complaining that there's no current Activity.
This would happen when calling `purchase()` in rapid succession. Here's the timeline of what would happen:
1. `purchase()`
2. `onActivityPaused()` --> Sets `ActivityProvider.activity` to null
3. A few milliseconds pass. If we call `purchase()` during this time, we crash. If we don't, we go to the next step.
4. `onActivityCreated()` --> Sets `ActivityProvider.activity` to `ProxyBillingActivity`
The fix is to not set the current Activity to null in `onActivityPaused()`. For all intents and purposes a paused Activity can still be considered the "current" Activity, until a new one is created. 
This avoids the crash, and makes the second invocation of `purchase()` return the expected …

Fixes a potential crash on Android when calling `purchase()` in rapid succession

---

.github/workflows/main.yml

Follow-up of https://github.com/RevenueCat/purchases-kmp/pull/494 for the `dependency-submission` GitHub Action, which has also [been failing](https://github.com/RevenueCat/purchases-kmp/actions/runs/18103475976/job/51512156080).

Update Gradle wrapper-validation to 4 for the `dependency-submission` GitHub Action

---

.gitmodules
renovate.json

We want to improve the developer experience (both for app developers and ourselves) of purchases-kmp, by removing the need to manually declare the PHC dependency in the iOS app. We will instead embed purchases-ios statically in the shipped `.klib`.
We'll do this incrementally. This is the first of many steps. It just adds purchases-ios as a submodule, but it's still unused. Later steps will make sure the purchases-ios source code gets compiled as part of the build, and included in the `.klib`.
- Adds purchases-ios as git submodule.
- Adds a Renovate config to keep it updated.
I purposefully did not set purchases-ios to the latest version, because I want to see if the Renovate config works. Renovate is kinda hard to test until it's all on `main`. We won't be using the submodule for a while …

Adds purchases-ios as git submodule
