RevenueCat/purchases-kmp

.github/workflows/main.yml, .github/workflows/pull_request.yml, build.gradle.kts, config/detekt/detekt.yml, core/build.gradle.kts, gradle/libs.versions.toml
=> Adds Detekt to check for missing documentation

.github/workflows/main.yml, .github/workflows/pull_request.yml, build.gradle.kts, core/api/core.api, datetime/api/datetime.api, either/api/either.api, gradle/libs.versions.toml, result/api/result.api
=> Add binary compatibility validator

core/api/core.api, core/src/androidMain/kotlin/io/shortway/kobankat/CustomerInfo.android.kt, core/src/commonMain/kotlin/io/shortway/kobankat/CustomerInfo.kt, core/src/iosMain/kotlin/io/shortway/kobankat/CustomerInfo.ios.kt
=> Fixes type error by renaming managementURL to managementUrlString

README.md
=> Adds note on migration to README.md

.circleci/config.yml, Dangerfile, Gemfile, Gemfile.lock
=> Adds the Danger bot.

.circleci/config.yml, VERSIONS.md, fastlane/.env.SAMPLE, fastlane/Fastfile, fastlane/README.md
Adds the required CircleCI config and Fastlane lanes to be able to couple KMP onto the release train. I tested this as far as I could, e.g. it opens the release PR and generates the changelog correctly. I'm thinking the real test comes when we release it for the first time. 
I did not yet set up the scheduled pipeline on CircleCI. Will do that when the SDK is fully ready.
=> Release train

.circleci/config.yml, fastlane/Fastfile, fastlane/README.md
=> Moves publishing logic from the CircleCI config to Fastlane.

apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/ProductCategoryAPI.kt, apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreProductAPI.kt, core/api/core.api, core/api/core.klib.api, core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/ProductCategory.android.kt, core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProduct.android.kt, core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/ProductCategory.kt, core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProduct.kt, core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/ProductCategory.ios.kt, core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProduct.ios.kt
It's nullable, because it can be unknown on Android. Deduced this from the Flutter implementation, so let me know if that's incorrect.
=> Adds ProductCategory to StoreProduct

README.md, migrations/KobanKat-MIGRATION.md
=> Adds KobanKat migration guide

core/src/commonTest/kotlin/com/revenuecat/purchases/kmp/PrintLnLogHandler.kt, core/src/commonTest/kotlin/com/revenuecat/purchases/kmp/PurchasesConfigurationTests.kt
=> Introduces PrintLnLogHandler to fix a test.

apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/InstallmentsInfoAPI.kt, apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/SubscriptionOptionAPI.kt, core/api/core.klib.api, core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/InstallmentsInfo.android.kt, core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/InstallmentsInfo.kt, core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.kt, core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/InstallmentsInfo.ios.kt, core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.ios.kt
This PR adds `InstallmentInfos` to the KMP SDK.
=> Add InstallmentInfos

core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/di/AndroidProvider.kt
=> Calls out WorkManager specifically in the initialization error message.

fastlane/Fastfile
=> :update_hybrid_common lane also updates mappings.podspec and models.podspec

mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offering.ios.kt
=> Fixes an incorrect cast to Package.

fastlane/Fastfile
=> Fixes a typo in the Fastfile.

Gemfile
=> Update Gemfile to fix dependabot

Gemfile.lock
Updating fastlane plugin to 5140dbc8c6d29a8ac6bccf9dd2f2b31f1f5d0437
=> Update fastlane plugin version

core/core.podspec, fastlane/Fastfile, mappings/mappings.podspec, models/models.podspec, revenuecatui/revenuecatui.podspec
As the title says. Also updates the version manually this time.
=> Make sure the version gets automatically updated in the podspec files too

.circleci/config.yml
=> Fixes requirements of the hold job.

revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitPaywall.kt
By default, Compose and UIKit interact in `Cooperative` mode. This means that for every scroll action, Compose is given the chance to react to it, before passing that on to the underlying UIKit (and in our case SwiftUI) view. This adds a noticeable delay to the scroll action, which is unnecessary in our case. We only ever need UIKit to respond to the scroll.
The fix is to use the `NonCooperative` mode. Unfortunately this is an experimental API. Since we would like to avoid binary incompatibility issues, this PR adds a best-effort approach. If the experimental API has changed in a newer CMP version that we happened to be linked against at runtime, we use the default (`NonCooperative`) mode. This would avoid a crash, at the cost of reintroducing the scrolling delay.  
Fixes #334.
=> Avoids unnecessary scrolling delay on iOS paywalls

build.gradle.kts, fastlane/Fastfile
=> Migrates publishing to Central Portal.

README.md
Added codelab instructions below:
1. [RevenueCat Google Play Integration](https://revenuecat.github.io/codelab/google-play/codelab-1-google-play-integration/index.html#0)
2. [Kotlin Multiplatform Purchases & Paywalls Overview](https://revenuecat.github.io/codelab/kmp/codelab-3-kmp-sdk/index.html#0)
=> Add Codelab instruction on the README file

CHANGELOG.md
=> Add warning with 2.x issues to all versions since 2.0.0 in CHANGELOG
